development:
  adapter: postgresql
  database: candle_database
  pool: 5
  timeout: 5000
  username: postgres
  password: 
test:
  adapter: postgresql
  database: candle_database
  pool: 5
  timeout: 5000
  username: postgres
  password:  

production:
  adapter: postgresql
  database: candle_database
  pool: 5
  timeout: 5000
  username: postgres
  password: 